version: 2
updates:
- package-ecosystem: pip
  directory: "/app"
  schedule:
    interval: daily
    time: '10:00'
  open-pull-requests-limit: 10
  reviewers:
  - abkfenris
- package-ecosystem: docker
  directory: "/app"
  schedule:
    interval: daily
    time: '10:00'
  open-pull-requests-limit: 10
# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  open-pull-requests-limit: 10
  schedule:
    interval: daily
    time: '10:00'
