version: 2
enable-beta-ecosystems: true
updates:
- package-ecosystem: "uv"
  directory: "/app"
  schedule:
    interval: daily
    time: '10:00'
  open-pull-requests-limit: 0
  cooldown:
      default-days: 7
  labels:
    - dependencies
- package-ecosystem: docker
  directory: "/app"
  schedule:
    interval: daily
    time: '10:00'
  open-pull-requests-limit: 0
  cooldown:
      default-days: 7
  labels:
    - dependencies
# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  open-pull-requests-limit: 0
  schedule:
    interval: daily
    time: '10:00'
  cooldown:
      default-days: 7
  labels:
    - dependencies
