repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        # exclude: tests/data
      - id: check-ast
      - id: check-yaml
        # exclude: services/config_gen/service_configs/data.neracoos.org_geoapi/pygeoapi.config.yaml
      - id: check-xml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-added-large-files

  # Looks for docstrings
  # - repo: https://github.com/econchick/interrogate
  #   rev: 1.5.0
  #   hooks:
  #     - id: interrogate
  #       # exclude: ^(docs|setup.py|tests)
  #       exclude: .*\/tests\/.*
  #       # args: [--config=pyproject.toml]
  #       args: [-vv]

  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.7
    hooks:
      - id: blackdoc

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: docs/source/conf.py
        args: [--max-line-length=105]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        additional_dependencies: [toml]
        args:
          [
            "--profile",
            "black",
            "--filter-files",
            "-p",
            "deployments",
            "-p",
            "forecasts",
          ]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.961
  #   hooks:
  #     - id: mypy
  #       name: mypy-common
  #       files: "common\/.*"
  #       args: [--ignore-missing-imports]
  #       additional_dependencies:
  #         [typing_extensions>=4.2.0, types-setuptools, types-PyYAML]
  #     - id: mypy
  #       name: mypy-fvcom
  #       files: "(common\/.*)|(datasets\/UMASS\/FVCOM\/.*)"
  #       args: [--ignore-missing-imports]
  #       additional_dependencies:
  #         [typing_extensions>=4.2.0, types-setuptools, types-PyYAML]
  #     - id: mypy
  #       name: mypy-bio
  #       files: "(common\/.*)|(datasets\/BIO\/WW3_72\/.*)"
  #       args: [--ignore-missing-imports]
  #       additional_dependencies:
  #         [typing_extensions>=4.2.0, types-setuptools, types-PyYAML]
  #     # - id: mypy
  #     #   name: mypy-cc-ports
  #     #   files: "(common\/.*)|(datasets\/NOAA\/PORTS\/.*)"
  #     #   args: [--ignore-missing-imports]
  #     #   additional_dependencies:
  #     #     [typing_extensions>=4.2.0, types-setuptools, types-PyYAML]
  #     - id: mypy
  #       name: mypy-config-gen
  #       files: "(common\/.*)|(services\/config_gen\/.*)"
  #       args: [--ignore-missing-imports]
  #       additional_dependencies:
  #         [typing_extensions>=4.2.0, types-setuptools, types-PyYAML]

  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.1.0
  #   hooks:
  #     - id: codespell
  #       args:
  #         - --quiet-level=2
  #         - --uri-ignore-words-list=BA
  # exclude: docs/cluster.drawio.svg

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
        args:
          - --py39-plus

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        exclude: .*\/tests\/.*

  - repo: https://github.com/zricethezav/gitleaks/
    rev: v8.15.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
  #       exclude: services/geoapi/data.neracoos.org_geoapi/entrypoint.sh

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.11.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.1"]
