repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        # exclude: tests/data
      - id: check-ast
      - id: check-yaml
      - id: check-xml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-added-large-files
      - id: no-commit-to-branch

  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.1.0
  #   hooks:
  #     - id: codespell
  #       args:
  #         - --quiet-level=2
  #         - --uri-ignore-words-list=BA
  # exclude: docs/cluster.drawio.svg

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        exclude: .*\/tests\/.*

  - repo: https://github.com/zricethezav/gitleaks/
    rev: v8.19.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  #       exclude: services/geoapi/data.neracoos.org_geoapi/entrypoint.sh

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.21.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.0"]

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 2.2.4
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.5
    hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix, --exit-non-zero-on-fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
