services:
  db-test:
    image: postgis/postgis:15-3.3@sha256:a2fc46b52819d25add4ed93d3da83e106e17ea3ace6883cce3791631c9820bb2
    env_file:
      - ./docker-data/test.env

  cache-test:
    image: redis:7.4.6-alpine@sha256:7a7c6b5c49a6896d0a58ee0c6dc0dcabe14f30f0a2f7d2d1362d276fa2d43166

  web-test:
    build: ./app
    image: gmri/neracoos-buoy-barn
    volumes:
      - ./app:/app:cached
      - /app/.venv
    env_file:
      - ./docker-data/test.env
    links:
      - db-test
      - cache-test
