# Generated by Django 2.1.2 on 2018-12-11 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deployments", "0006_timeseries_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeseries",
            name="buffer_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="deployments.BufferType",
            ),
        ),
        migrations.AlterField(
            model_name="timeseries",
            name="depth",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
