# Generated by Django 2.1.2 on 2018-12-11 21:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("deployments", "0008_auto_20181211_1656"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                null=True,
                srid=4326,
                verbose_name="Location",
            ),
        ),
    ]
