# Generated by Django 2.1.2 on 2018-12-13 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("deployments", "0009_platform_geom"),
    ]

    operations = [
        migrations.RenameField(
            model_name="platform",
            old_name="mooring_site_Desc",
            new_name="mooring_site_desc",
        ),
    ]
