# Generated by Django 2.1.2 on 2018-12-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0011_auto_20181220_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
