# Generated by Django 2.1.2 on 2019-01-04 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0012_platform_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateField(auto_now_add=True)),
                ("end_time", models.DateField(blank=True, null=True)),
                ("message", models.TextField()),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deployments.Platform",
                    ),
                ),
            ],
        ),
    ]
