# Generated by Django 2.1.2 on 2019-01-07 21:20

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0014_auto_20190104_2018"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("erddap_dataset", models.CharField(max_length=256)),
                ("invertLongitude", models.BooleanField()),
                ("name", models.TextField()),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[("waveHeight", "Wave Height")],
                        max_length=32,
                    ),
                ),
                (
                    "erddap_server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deployments.ErddapServer",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="alert",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="deployments.Platform",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="start_time",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
