# Generated by Django 2.1.2 on 2019-01-08 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("deployments", "0017_auto_20190107_2156"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forecast",
            name="erddap_server",
        ),
        migrations.DeleteModel(
            name="Forecast",
        ),
    ]
