# Generated by Django 2.1.5 on 2019-03-28 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0018_auto_20190108_1912"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErddapDataset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deployments.ErddapServer",
                    ),
                ),
            ],
        ),
    ]
