# Generated by Django 2.1.5 on 2019-03-28 15:33

from django.db import migrations


def create_and_connect_datasets(apps, schema_editory):
    """
    Create and connect datasets to timeseries
    """
    ErddapDataset = apps.get_model("deployments", "ErddapDataset")
    TimeSeries = apps.get_model("deployments", "TimeSeries")

    for ts in TimeSeries.objects.all():
        ds = ErddapDataset.objects.filter(
            name=ts.erddap_dataset, server=ts.erddap_server
        ).first()
        if not ds:
            ds = ErddapDataset(name=ts.erddap_dataset, server=ts.erddap_server)
            ds.save()
        ts.dataset = ds
        ts.save()


class Migration(migrations.Migration):

    dependencies = [("deployments", "0021_auto_20190328_1520")]

    operations = [migrations.RunPython(create_and_connect_datasets)]
