# Generated by Django 2.1.5 on 2019-03-28 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0022_Create and connect datasets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeseries",
            name="erddap_dataset",
        ),
        migrations.RemoveField(
            model_name="timeseries",
            name="erddap_server",
        ),
        migrations.AlterField(
            model_name="timeseries",
            name="dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="deployments.ErddapDataset",
            ),
        ),
    ]
