# Generated by Django 2.2 on 2019-04-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deployments", "0025_auto_20190328_1744"),
    ]

    operations = [
        migrations.AddField(
            model_name="erddapdataset",
            name="healthchech_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
