# Generated by Django 3.1.1 on 2020-09-17 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0028_auto_20200407_1335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deployment',
        ),
    ]
