# Generated by Django 3.1.1 on 2020-09-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("deployments", "0029_delete_deployment")]

    operations = [
        migrations.AlterField(
            model_name="timeseries",
            name="constraints",
            field=models.JSONField(
                blank=True,
                help_text="Extra constratints needed when querying ERDDAP (for example: when datasets have multiple platforms)",
                null=True,
                verbose_name="Extra ERDDAP constraints",
            ),
        )
    ]
