# Generated by Django 3.2 on 2021-04-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("deployments", "0035_erddapdataset_greater_than_hourly")]

    operations = [
        migrations.AlterField(
            model_name="datatype",
            name="short_name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
