# Generated by Django 3.2 on 2021-04-16 15:05

from django.db import migrations


def create_unh_data_types(apps, schema_editor):
    data_types = [
        (
            "mole_concentration_of_carbon_dioxide_in_air_ppm",
            "PPM Atmospheric Carbon Dioxide",
            "Atmospheric Concentration of Carbon Dioxide in Parts Per Million",
            "ppm",
        ),
        (
            "surface_partial_pressure_of_carbon_dioxide_in_sea_water_ppm",
            "PPM Sea Water Carbon Dioxide",
            "Sea Water Concentration of Carbon Dioxide in Parts Per Million",
            "ppm",
        ),
        (
            "moles_of_oxygen_per_unit_mass_in_sea_water_um_kg",
            "uM Oxygen per kg Sea Water",
            "Micro Moles Oxygen per Kilogram of Sea Water",
            "uM/kg",
        ),
        (
            "omega_aragonite",
            "Omega Aragonite",
            "Omega Aragonite - Derived from total alkalinity and pCO2",
            "Omega",
        ),
    ]

    DataType = apps.get_model("deployments", "DataType")

    for standard_name, short_name, long_name, unit in data_types:
        instance = DataType(
            standard_name=standard_name,
            short_name=short_name,
            long_name=long_name,
            units=unit,
        )
        instance.save()


def empty_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [("deployments", "0036_alter_datatype_short_name")]

    operations = [migrations.RunPython(create_unh_data_types, empty_reverse)]
