# Generated by Django 3.2 on 2021-04-19 18:53

from django.db import migrations


def create_unh_data_types(apps, schema_editor):
    data_types = [
        (
            "omega_calcite",
            "Omega Calcite",
            "Omega Calcite - Derived from total alkalinity and pCO2",
            "Omega",
        ),
    ]

    DataType = apps.get_model("deployments", "DataType")

    for standard_name, short_name, long_name, unit in data_types:
        instance = DataType(
            standard_name=standard_name,
            short_name=short_name,
            long_name=long_name,
            units=unit,
        )
        instance.save()


def empty_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [("deployments", "0037_generate_unh_datatypes")]

    operations = [migrations.RunPython(create_unh_data_types, empty_reverse)]
