# Generated by Django 3.2 on 2021-04-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("deployments", "0038_generate_unh_ommega_calcite")]

    operations = [
        migrations.AddField(
            model_name="erddapserver",
            name="proxy_cors",
            field=models.BooleanField(
                default=True,
                help_text="Use Buoy Barn to proxy requests to remote ERDDAP server, if the remote server does not support CORS",
                verbose_name="Proxy CORS requests",
            ),
        )
    ]
