# Generated by Django 4.2.4 on 2023-09-14 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("deployments", "0041_erddapdataset_unique_dataset"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timeseries",
            options={"ordering": ["data_type"]},
        ),
    ]
