# Generated by Django 4.2.4 on 2023-09-14 15:20

from django.db import migrations


def create_tide_data_types(apps, schema_editor):
    data_types = [
        (
            "sea_surface_height_above_geopotential_datum",
            "Sea Surface Height",
            "Sea surface height above geopotential datum (NAVD 88)",
            "Meters",
        ),
        (
            "tidal_sea_surface_height_above_mean_higher_high_water",
            "MHHW",
            "Mean Higher High Water",
            "Meters",
        ),
        (
            "tidal_sea_surface_height_above_mean_sea_level",
            "MSL",
            "Mean Sea Level",
            "Meters",
        ),
        (
            "tidal_sea_surface_height_above_mean_lower_low_water",
            "MLLW",
            "Mean Lower Low Water",
            "Meters",
        ),
    ]

    DataType = apps.get_model("deployments", "DataType")

    for standard_name, short_name, long_name, unit in data_types:
        instance = DataType(
            standard_name=standard_name,
            short_name=short_name,
            long_name=long_name,
            units=unit,
        )
        instance.save()


def empty_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("deployments", "0042_alter_timeseries_options"),
    ]

    operations = [migrations.RunPython(create_tide_data_types, empty_reverse)]
