# Generated by Django 4.2.4 on 2023-09-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deployments", "0043_tide_data_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="platform_type",
            field=models.CharField(
                choices=[("Buoy", "Buoy"), ("Tide Station", "Tide Station")],
                default="Buoy",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="timeseries",
            name="datum_mhhw_meters",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Mean Higher High Water (MHHW) offset in meters",
            ),
        ),
        migrations.AddField(
            model_name="timeseries",
            name="datum_mhw_meters",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Mean High Water (MHW) offset in meters",
            ),
        ),
        migrations.AddField(
            model_name="timeseries",
            name="datum_mllw_meters",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Mean Lower Low Water (MLLW) offset in meters",
            ),
        ),
        migrations.AddField(
            model_name="timeseries",
            name="datum_mlw_meters",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Mean Low Water (MLW) offset in meters",
            ),
        ),
        migrations.AddField(
            model_name="timeseries",
            name="datum_msl_meters",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Mean Sea Level (MSL) offset in meters",
            ),
        ),
        migrations.AddField(
            model_name="timeseries",
            name="datum_mtl_meters",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Mean Tide Level (MTL) offset in meters",
            ),
        ),
    ]
