# Generated by Django 5.0 on 2023-12-29 16:09

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "deployments",
            "0044_platform_platform_type_timeseries_datum_mhhw_meters_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timeseries",
            options={"ordering": ["data_type"], "verbose_name_plural": "Time Series"},
        ),
        migrations.AlterField(
            model_name="timeseries",
            name="start_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name="FloodLevel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_value", models.FloatField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("MINOR", "Minor"),
                            ("MODERATE", "Moderate"),
                            ("MAJOR", "Major"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                        verbose_name="Level",
                    ),
                ),
                ("level_other", models.TextField(blank=True, null=True)),
                (
                    "timeseries",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flood_levels",
                        to="deployments.timeseries",
                    ),
                ),
            ],
        ),
    ]
