# Generated by Django 5.0 on 2023-12-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "deployments",
            "0045_alter_timeseries_options_alter_timeseries_start_time_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="floodlevel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="floodlevel",
            name="level_other",
            field=models.CharField(blank=True, null=True),
        ),
    ]
