# Generated by Django 5.0.1 on 2024-01-11 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deployments", "0046_floodlevel_description_alter_floodlevel_level_other"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floodlevel",
            name="level_other",
            field=models.CharField(
                blank=True,
                null=True,
                verbose_name="Optional name for 'Other level'",
            ),
        ),
        migrations.CreateModel(
            name="PlatformLinks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="URL title")),
                ("url", models.CharField(max_length=512, verbose_name="URL")),
                (
                    "alt_text",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Alternate text",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="deployments.platform",
                    ),
                ),
            ],
        ),
    ]
