# Generated by Django 5.1.1 on 2024-11-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deployments", "0051_timeseries_highlighted"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeseries",
            name="extrama",
            field=models.BooleanField(
                default=False,
                help_text="Is this timeseries an extrema (high or low), or regularly spaced?",
            ),
        ),
        migrations.AddField(
            model_name="timeseries",
            name="timeseries_type",
            field=models.CharField(
                choices=[
                    ("Observation", "Observation"),
                    ("Prediction", "Prediction"),
                    ("Forecast", "Foreacst"),
                    ("Climatology", "Climatology"),
                ],
                default="Observation",
                help_text="Is this timeseries an observation, prediction, forecast, or climatology?",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="platform_type",
            field=models.CharField(
                choices=[
                    ("Buoy", "Buoy"),
                    ("Tide Station", "Tide Station"),
                    ("Overland Flood", "Overland Flood"),
                ],
                default="Buoy",
                max_length=50,
            ),
        ),
    ]
