# Generated by Django 5.1.1 on 2024-11-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0052_timeseries_extrama_timeseries_timeseries_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeseries',
            old_name='extrama',
            new_name='extrema',
        ),
    ]
