# Generated by Django 5.1.4 on 2025-03-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deployments", "0056_erddapdataset_public_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="visible_climatology",
            field=models.BooleanField(default=True, verbose_name="Visible on Climatology tool"),
        ),
        migrations.AddField(
            model_name="platform",
            name="visible_dev",
            field=models.BooleanField(default=True, verbose_name="Visible on dev Mariner's Dashboard"),
        ),
        migrations.AddField(
            model_name="platform",
            name="visible_mariners",
            field=models.BooleanField(default=True, verbose_name="Visible on Mariner's Dashboard"),
        ),
    ]
