# Generated by Django 5.2.5 on 2025-08-14 17:44

from django.db import migrations, models


def active_to_visible_mariners(apps, schema_editor):
    Platform = apps.get_model("deployments", "Platform")
    for platform in Platform.objects.all():
        platform.visible_mariners = platform.active
        platform.save()


def visible_mariners_to_active(apps, schema_editor):
    Platform = apps.get_model("deployments", "Platform")
    for platform in Platform.objects.all():
        platform.active = platform.visible_mariners
        platform.save()


class Migration(migrations.Migration):
    dependencies = [
        ("deployments", "0058_alter_platform_platform_type"),
    ]

    operations = [
        migrations.RunPython(active_to_visible_mariners, visible_mariners_to_active),
        migrations.RemoveField(
            model_name="platform",
            name="active",
        ),
        migrations.AlterField(
            model_name="platform",
            name="visible_climatology",
            field=models.BooleanField(default=False, verbose_name="Visible on Climatology tool"),
        ),
    ]
