# Generated by Django 5.2.5 on 2025-08-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deployments", "0059_remove_platform_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="visible_graph_download",
            field=models.BooleanField(default=True, verbose_name="Visible on Graph Download tool"),
        ),
    ]
