# Generated by Django 5.2.7 on 2026-01-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deployments", "0060_platform_visible_graph_download"),
    ]

    operations = [
        migrations.AddField(
            model_name="erddapserver",
            name="mqtt_broker",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="MQTT broker"),
        ),
        migrations.AddField(
            model_name="erddapserver",
            name="mqtt_password",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="MQTT Password"),
        ),
        migrations.AddField(
            model_name="erddapserver",
            name="mqtt_port",
            field=models.PositiveIntegerField(default=1883, verbose_name="MQTT Port"),
        ),
        migrations.AddField(
            model_name="erddapserver",
            name="mqtt_username",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="MQTT Username"),
        ),
    ]
