# Generated by Django 5.2.12 on 2026-03-27 14:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("deployments", "0061_erddapserver_mqtt_broker_erddapserver_mqtt_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platform",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                null=True,
                srid=4326,
                verbose_name="Location",
            ),
        ),
    ]
