# Generated by Django 6.0.7 on 2026-09-08 16:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deployments", "0062_alter_platform_geom"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("end_time_retired", "End Time Retired"),
                            ("end_time_cleared", "End Time Cleared"),
                            ("backoff_increased", "Backoff Increased"),
                            ("not_found", "Not Found"),
                            ("forbidden", "Forbidden"),
                            ("unrecognized_variable", "Unrecognized Variable"),
                            ("unrecognized_constraint", "Unrecognized Constraint"),
                            ("server_error", "Server Error"),
                            ("unknown_error", "Unknown Error"),
                            ("constraint_out_of_range", "Constraint Out Of Range"),
                            ("no_matching_time", "No Matching Time"),
                            ("time_range_reported", "Time Range Reported"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "constraint_group",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The `metrics.constraint_group_id()` hash of the constraints this message concerns, or blank for a subject with no constraint group. Distinguishes messages for the same subject and code raised against different constraint groups, so two depths on the same dataset each get their own row instead of clobbering one another -- and so a message joins to the buoybarn.erddap.constraint_group.info metric.",
                        max_length=16,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("info", "Info"), ("warning", "Warning"), ("danger", "Danger")],
                        max_length=16,
                    ),
                ),
                ("message", models.TextField()),
                ("context", models.JSONField(blank=True, default=dict)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("occurrences", models.PositiveIntegerField(default=1)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_messages",
                        to="deployments.erddapdataset",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_messages",
                        to="deployments.platform",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_messages",
                        to="deployments.erddapserver",
                    ),
                ),
                (
                    "timeseries",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_messages",
                        to="deployments.timeseries",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("dataset__isnull", True),
                                ("platform__isnull", False),
                                ("server__isnull", True),
                                ("timeseries__isnull", True),
                            ),
                            models.Q(
                                ("dataset__isnull", True),
                                ("platform__isnull", True),
                                ("server__isnull", True),
                                ("timeseries__isnull", False),
                            ),
                            models.Q(
                                ("dataset__isnull", False),
                                ("platform__isnull", True),
                                ("server__isnull", True),
                                ("timeseries__isnull", True),
                            ),
                            models.Q(
                                ("dataset__isnull", True),
                                ("platform__isnull", True),
                                ("server__isnull", False),
                                ("timeseries__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="system_message_exactly_one_subject",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("platform__isnull", False)),
                        fields=("platform", "code", "constraint_group"),
                        name="unique_platform_system_message",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("timeseries__isnull", False)),
                        fields=("timeseries", "code", "constraint_group"),
                        name="unique_timeseries_system_message",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("dataset__isnull", False)),
                        fields=("dataset", "code", "constraint_group"),
                        name="unique_dataset_system_message",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("server__isnull", False)),
                        fields=("server", "code", "constraint_group"),
                        name="unique_server_system_message",
                    ),
                ],
            },
        ),
    ]
