# Generated by Django 6.0.7 on 2026-09-07 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("deployments", "0062_alter_platform_geom"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("end_time_retired", "End Time Retired"),
                            ("end_time_cleared", "End Time Cleared"),
                            ("backoff_increased", "Backoff Increased"),
                            ("not_found", "Not Found"),
                            ("forbidden", "Forbidden"),
                            ("unrecognized_variable", "Unrecognized Variable"),
                            ("unrecognized_constraint", "Unrecognized Constraint"),
                            ("server_error", "Server Error"),
                            ("unknown_error", "Unknown Error"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "constraint_group",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The `metrics.constraint_group_id()` hash of the constraints this message concerns, or blank for a subject with no constraint group. Distinguishes messages for the same subject and code raised against different constraint groups, so two depths on the same dataset each get their own row instead of clobbering one another -- and so a message joins to the buoybarn.erddap.constraint_group.info metric.",
                        max_length=16,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("info", "Info"), ("warning", "Warning"), ("danger", "Danger")],
                        max_length=16,
                    ),
                ),
                ("message", models.TextField()),
                ("context", models.JSONField(blank=True, default=dict)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("occurrences", models.PositiveIntegerField(default=1)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id", "code", "constraint_group"),
                        name="unique_system_message",
                    ),
                ],
            },
        ),
    ]
