# Generated by Django 6.0.7 on 2026-09-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0063_systemmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmessage',
            name='code',
            field=models.CharField(choices=[('end_time_retired', 'End Time Retired'), ('end_time_cleared', 'End Time Cleared'), ('backoff_increased', 'Backoff Increased'), ('not_found', 'Not Found'), ('forbidden', 'Forbidden'), ('unrecognized_variable', 'Unrecognized Variable'), ('unrecognized_constraint', 'Unrecognized Constraint'), ('server_error', 'Server Error'), ('unknown_error', 'Unknown Error'), ('constraint_out_of_range', 'Constraint Out Of Range'), ('no_matching_time', 'No Matching Time'), ('time_range_reported', 'Time Range Reported')], max_length=64),
        ),
    ]
