[tool]
[tool.poetry]
name = "buoy_barn"
version = "0.4.4"
description = "NERACOOS lightweight API sitting in front of ERDDAP"
authors = ["Alex Kerney <akerney@gmri.org>"]

[tool.poetry.dependencies]
python = "^3.9"
celery = "^5.2"
django = "^4.0"
django-cors-headers = "^3.11"
django-debug-toolbar = "^3.2"
django-memoize = "^2.3.1"
django-redis = "^5.2"
djangorestframework = "^3.13"
djangorestframework-gis = "^0.18"
erddapy = "1.2.1"
freezegun = "^1.2.1"
geojson = "^2.5.0"
netcdf4 = "^1.5.8"
psycopg2-binary = "^2.9.3"
sentry-sdk = "^1.5.8"
uwsgi = "^2.0.20"
vcrpy = "^4.1"
whitenoise = "^6.0"
xarray = "^2022.3.0"
pandas = "^1.4.1"
prefect = "^1.1.0"

[tool.poetry.dev-dependencies]
ipython = "^8.1"
pyyaml = "^6.0"
pytest = "^7.1"
pytest-django = "^4.5"
pytest-cov = "^3.0"
prospector = {version = "^1.7", extras = ["with_mypy", "with_vulture"]}
