[tool]
[tool.poetry]
name = "buoy_barn"
version = "0.1.8"
description = "NERACOOS lightweight API sitting in front of ERDDAP"
authors = ["Alex Kerney <akerney@gmri.org>"]

[tool.poetry.dependencies]
python = "^3.7"
celery = "^4.4"
django = "^3.0"
django-cors-headers = "^3.4"
django-debug-toolbar = "^2.2"
django-memoize = "^2.3.1"
django-redis = "^4.12"
djangorestframework = "^3.11"
djangorestframework-gis = "^0.15"
erddapy = "^0.5.3"
freezegun = "^0.3.15"
geojson = "^2.5.0"
netcdf4 = "^1.5.3"
psycopg2-binary = "^2.8.5"
sentry-sdk = "^0.16.2"
uwsgi = "^2.0.19"
vcrpy = "^4.0"
whitenoise = "^5.1"
xarray = "^0.16.0"
pandas = "^1.0"

[tool.poetry.dev-dependencies]
ipython = "^7.16"
pyyaml = "^5.3.1"
pytest = "^5.4"
pytest-django = "^3.9"
pytest-cov = "^2.10"
prospector = {version = "^1.3", extras = ["with_mypy", "with_vulture"]}
