[tool]
[tool.poetry]
name = "buoy_barn"
version = "0.4.9"
description = "NERACOOS lightweight API sitting in front of ERDDAP"
authors = ["Alex Kerney <akerney@gmri.org>"]

[tool.poetry.dependencies]
python = "^3.10"
celery = "^5.2"
django = "^4.1"
django-cors-headers = "^3.13"
django-debug-toolbar = "^3.7"
django-memoize = "^2.3.1"
django-redis = "^5.2"
djangorestframework = "^3.14"
djangorestframework-gis = "^1.0"
erddapy = "1.2.1"
freezegun = "^1.2.1"
geojson = "^2.5.0"
netcdf4 = "^1.6.0"
psycopg2-binary = "^2.9.5"
sentry-sdk = "^1.8.0"
uwsgi = "^2.0.20"
vcrpy = "^4.2"
whitenoise = "^6.2"
xarray = "^2022.3.0"
pandas = "^1.4.3"
prefect = "^1.4.0"
django-health-check = "^3.17.0"

[tool.poetry.dev-dependencies]
ipython = "^8.4"
pyyaml = "^6.0"
pytest = "^7.1"
pytest-django = "^4.5"
pytest-cov = "^4.0"
prospector = { version = "^1.7", extras = ["with_mypy", "with_vulture"] }
