[tool]
[tool.poetry]
name = "buoy_barn"
version = "0.4.1"
description = "NERACOOS lightweight API sitting in front of ERDDAP"
authors = ["Alex Kerney <akerney@gmri.org>"]

[tool.poetry.dependencies]
python = "^3.9"
celery = "^5.2"
django = "^3.2"
django-cors-headers = "^3.10"
django-debug-toolbar = "^3.2"
django-memoize = "^2.3.1"
django-redis = "^5.2"
djangorestframework = "^3.12"
djangorestframework-gis = "^0.17"
erddapy = "1.2.0"
freezegun = "^1.1.0"
geojson = "^2.5.0"
netcdf4 = "^1.5.8"
psycopg2-binary = "^2.9.3"
sentry-sdk = "^1.5.0"
uwsgi = "^2.0.20"
vcrpy = "^4.1"
whitenoise = "^5.3"
xarray = "^0.21.1"
pandas = "^1.3.4"
prefect = "^0.15.9"

[tool.poetry.dev-dependencies]
ipython = "^8.1"
pyyaml = "^6.0"
pytest = "^7.0"
pytest-django = "^4.5"
pytest-cov = "^3.0"
prospector = {version = "^1.7", extras = ["with_mypy", "with_vulture"]}
