[tool]
[tool.poetry]
name = "buoy_barn"
version = "0.0.0"
description = "NERACOOS lightweight API sitting in front of ERDDAP"
authors = ["Alex Kerney <akerney@gmri.org>"]

[tool.poetry.dependencies]
python = "^3.7"
celery = {version = "==4.3.0", extras = ["redis"]}
django = "==2.2.5"
django-cors-headers = "==3.1.0"
django-debug-toolbar = "==2.0"
django-memoize = "==2.2.0"
django-redis = "==4.10.0"
djangorestframework = "==3.10.3"
djangorestframework-gis = "==0.14"
erddapy = "==0.5.0"
freezegun = "==0.3.12"
geojson = "==2.5.0"
netcdf4 = "==1.5.3"
psycopg2-binary = "==2.8.4"
sentry-sdk = "==0.13.4"
uwsgi = "==2.0.18"
vcrpy = "==2.1.0"
whitenoise = "==4.1.3"
xarray = "^0.15.0"
pandas = "<1.0"

[tool.poetry.dev-dependencies]
ipython = "==7.10.0"
pyyaml = "==5.1.2"
pytest = "^5.3"
pytest-django = "^3.8"
pytest-cov = "^2.8"
prospector = {version = "==1.1.7", extras = ["with_mypy", "with_vulture"]}
