[tool]
[tool.poetry]
name = "buoy_barn"
version = "0.5.0"
description = "NERACOOS lightweight API sitting in front of ERDDAP"
authors = ["Alex Kerney <akerney@gmri.org>"]

[tool.poetry.dependencies]
python = "^3.10"
celery = "^5.3"
django = "^4.2"
django-cors-headers = "^4.2"
django-debug-toolbar = "^4.2"
django-memoize = "^2.3.1"
django-redis = "^5.4"
djangorestframework = "^3.14"
djangorestframework-gis = "^1.0"
erddapy = "1.2.1"
freezegun = "^1.2.1"
geojson = "^2.5.0"
netcdf4 = "^1.6.4"
psycopg2-binary = "^2.9.9"
sentry-sdk = "^1.32.0"
uwsgi = "^2.0.22"
vcrpy = "^5.1"
whitenoise = "^6.6"
xarray = "^2023.9.0"
pandas = "^1.5.3"
prefect = "^1.4.0"
django-health-check = "^3.17.0"

[tool.poetry.dev-dependencies]
ipython = "^8.16"
pyyaml = "^6.0"
pytest = "^7.4"
pytest-django = "^4.5"
pytest-cov = "^4.1"
prospector = { version = "^1.10", extras = ["with_mypy", "with_vulture"] }
