[tool]
[tool.poetry]
name = "buoy_barn"
version = "0.3.6"
description = "NERACOOS lightweight API sitting in front of ERDDAP"
authors = ["Alex Kerney <akerney@gmri.org>"]

[tool.poetry.dependencies]
python = "^3.9"
celery = "^5.1"
django = "^3.2"
django-cors-headers = "^3.7"
django-debug-toolbar = "^3.2"
django-memoize = "^2.3.1"
django-redis = "^5.0"
djangorestframework = "^3.12"
djangorestframework-gis = "^0.17"
erddapy = "1.0.0"
freezegun = "^1.1.0"
geojson = "^2.5.0"
netcdf4 = "^1.5.7"
psycopg2-binary = "^2.9.1"
sentry-sdk = "^1.3.0"
uwsgi = "^2.0.19"
vcrpy = "^4.1"
whitenoise = "^5.2"
xarray = "^0.18.2"
pandas = "^1.2.4"
prefect = "^0.15.1"

[tool.poetry.dev-dependencies]
ipython = "^7.25"
pyyaml = "^5.4"
pytest = "^6.2"
pytest-django = "^4.4"
pytest-cov = "^2.12"
prospector = {version = "^1.3", extras = ["with_mypy", "with_vulture"]}
