[tool]
[tool.poetry]
name = "buoy_barn"
version = "0.1.18"
description = "NERACOOS lightweight API sitting in front of ERDDAP"
authors = ["Alex Kerney <akerney@gmri.org>"]

[tool.poetry.dependencies]
python = "^3.7"
celery = "^5.0"
django = "^3.1"
django-cors-headers = "^3.7"
django-debug-toolbar = "^3.2"
django-memoize = "^2.3.1"
django-redis = "^4.12"
djangorestframework = "^3.12"
djangorestframework-gis = "^0.17"
erddapy = "0.9.0"
freezegun = "^1.1.0"
geojson = "^2.5.0"
netcdf4 = "^1.5.5"
psycopg2-binary = "^2.8.6"
sentry-sdk = "^0.19.5"
uwsgi = "^2.0.19"
vcrpy = "^4.1"
whitenoise = "^5.2"
xarray = "^0.16.2"
pandas = "<2.0.0"

[tool.poetry.dev-dependencies]
ipython = "^7.20"
pyyaml = "^5.4"
pytest = "^6.2"
pytest-django = "^4.1"
pytest-cov = "^2.11"
prospector = {version = "^1.3", extras = ["with_mypy", "with_vulture"]}
