[tool]
[tool.poetry]
name = "buoy_barn"
version = "0.1.9"
description = "NERACOOS lightweight API sitting in front of ERDDAP"
authors = ["Alex Kerney <akerney@gmri.org>"]

[tool.poetry.dependencies]
python = "^3.7"
celery = "^4.4"
django = "^3.1"
django-cors-headers = "^3.5"
django-debug-toolbar = "^2.2"
django-memoize = "^2.3.1"
django-redis = "^4.12"
djangorestframework = "^3.11"
djangorestframework-gis = "^0.16"
erddapy = "0.5.3"
freezegun = "^1.0.0"
geojson = "^2.5.0"
netcdf4 = "^1.5.4"
psycopg2-binary = "^2.8.6"
sentry-sdk = "^0.17.7"
uwsgi = "^2.0.19"
vcrpy = "^4.1"
whitenoise = "^5.2"
xarray = "^0.16.1"
pandas = "<1.0.0"

[tool.poetry.dev-dependencies]
ipython = "^7.18"
pyyaml = "^5.3.1"
pytest = "^6.0"
pytest-django = "^3.10"
pytest-cov = "^2.10"
prospector = {version = "^1.3", extras = ["with_mypy", "with_vulture"]}
