[tool]
[tool.poetry]
name = "buoy_barn"
version = "0.6.4"
description = "NERACOOS lightweight API sitting in front of ERDDAP"
authors = ["Alex Kerney <akerney@gmri.org>"]

[tool.poetry.dependencies]
python = "^3.10"
celery = "^5.3"
django = "^5.0"
django-cors-headers = "^4.3"
django-debug-toolbar = "^4.3"
django-memoize = "^2.3.1"
django-redis = "^5.4"
djangorestframework = "^3.15"
djangorestframework-gis = "^1.0"
erddapy = "1.2.1"
freezegun = "^1.4.0"
geojson = "^3.1.0"
netcdf4 = "^1.6.5"
psycopg2-binary = "^2.9.9"
sentry-sdk = "^1.45.0"
uwsgi = "^2.0.24"
vcrpy = "^6.0"
whitenoise = "^6.6"
xarray = "^2024.1.1"
pandas = "^1.5.3"
django-health-check = "^3.18.1"
pystac = "^1.9.0"
flower = "^2.0.1"
slack-sdk = "^3.27.1"

[tool.poetry.dev-dependencies]
ipython = "^8.22"
pyyaml = "^6.0"
pytest = "^8.1"
pytest-django = "^4.8"
pytest-cov = "^5.0"
prospector = { version = "^1.10", extras = ["with_mypy", "with_vulture"] }
