# Generated by Django 2.1.2 on 2018-12-04 16:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BufferType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Buffer type')),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_name', models.CharField(max_length=128)),
                ('short_name', models.CharField(max_length=16)),
                ('long_name', models.CharField(max_length=128)),
                ('units', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deploment_name', models.CharField(max_length=50, verbose_name='Deployment platform name')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('magnetic_variation', models.FloatField()),
                ('water_depth', models.FloatField()),
                ('mooring_site_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MooringType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Mooring type')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Platform name')),
                ('mooring_site_Desc', models.TextField(verbose_name='Mooring Site Description')),
                ('nbdc_site_id', models.CharField(max_length=100, null=True)),
                ('uscg_light_letter', models.CharField(max_length=10, null=True)),
                ('uscg_light_num', models.CharField(max_length=16, null=True)),
                ('watch_circle_radius', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('website', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Station type')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(default=0)),
                ('buffer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.BufferType')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.DataType')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.Deployment')),
            ],
        ),
        migrations.AddField(
            model_name='platform',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.Program'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='mooring_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.MooringType'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.Platform'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='station_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.StationType'),
        ),
    ]
