# Generated by Django 2.1.2 on 2018-12-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_auto_20181204_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='deploment_name',
            new_name='deployment_name',
        ),
        migrations.AlterField(
            model_name='deployment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
