apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: buoy-barn-cache
  labels:
    service: redis
    tier: backend
    role: cache
spec:
  selector:
    matchLabels:
      service: redis
      tier: backend
      role: cache
  serviceName: buoy-barn-cache
  replicas: 1
  template:
    metadata:
      labels:
        service: redis
        tier: backend
        role: cache
    spec:
      containers:
        - name: redis
          image: redis:5.0.5-alpine
          ports:
            - containerPort: 6379
  volumeClaimTemplates: []
