apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: celery
    tier: backend
    role: flower
  name: flower
spec:
  selector:
    matchLabels:
      service: celery
      tier: backend
      role: flower
  template:
    metadata:
      labels:
        service: celery
        tier: backend
        role: flower
    spec:
      containers:
        - name: flower
          image: gmri/neracoos-buoy-barn
          args:
            - celery
            - -A
            - buoy_barn
            - flower
            - -l
            - info
          ports:
            - containerPort: 5555
              name: http
          envFrom:
            - secretRef:
                name: buoy-barn-secrets
            - configMapRef:
                name: buoy-barn-config
          env:
            - name: DJANGO_MANAGEPY_MIGRATE
              value: "on"
            - name: DJANGO_MANAGEPY_COLLECTSTATIC
              value: "off"
          volumeMounts:
            - name: django-static
              mountPath: /static
      volumes:
        - name: django-static
          emptyDir: {}
