apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: web
    app: buoy-barn
  name: web
spec:
  template:
    metadata:
      labels:
        service: web
        app: buoy-barn
    spec:
      containers:
        - args:
            - uwsgi
            - --module=buoy_barn.wsgi:application
            - --master
            - --pidfile=/tmp/project-master.pid
            - --http
            - :8080
            - --uid=1000
            - --gid=2000
            - --max-requests=5000
            - --vacuum
            - --processes
            - "4"
          envFrom:
            - secretRef:
                name: buoy-barn-secrets
            - configMapRef:
                name: buoy-barn-config
          env:
            - name: DJANGO_MANAGEPY_MIGRATE
              value: "on"
            - name: DJANGO_MANAGEPY_COLLECTSTATIC
              value: "on"
            - name: POSTGRES_HOST
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
            - name: SECRET_KEY
            - name: SENTRY_DSN
          image: grmi/buoy-barn
          name: web
          ports:
            - containerPort: 8080
              name: http
          resources: {}
