apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: buoy-barn-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: web
              servicePort: 8080
