apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: buoy-barn-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8080
