apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: buoy-barn-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    # nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost http://mariners.neracoos.org https://mariners.neracoos.org http://localhost:3000"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  rules:
    - host: buoybarn.neracoos.org
      http:
        paths:
          - path: /
            backend:
              serviceName: web
              servicePort: 8080
