namespace: buoy-barn
resources:
  - docker-hub-secret.yaml
  - cache.yaml
  - cache-service.yaml
  - deployment.yaml
  - ingress.yaml
  - web-service.yaml
configMapGenerator:
  - name: buoy-barn-config
    env: config.env
secretGenerator:
  - name: buoy-barn-secrets
    env: secret.env
commonLabels:
  app: buoy-barn
  maintainer: akerney
  funder: NERACOOS
  project: Mariners_dashboard
