namespace: buoy-barn
resources:
  - cache.yaml
  - cache-service.yaml
  - deployment.yaml
  - ingress.yaml
  - web-service.yaml
  - celery-worker.yaml
  - celery-beat.yaml
  - celery-flower.yaml
  - celery-flower-service.yaml
configMapGenerator:
  - name: buoy-barn-config
    envs:
    - config.env
