name: CI

on: [push]
env:
  BUILDX_CACHE: /tmp/.buildx-cache
  CACHE_KEY: buoy-barn-buildx-

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Docker Data
        run: |
          mkdir docker-data
          cat <<< "${{ secrets.DOCKER_DATA_SECRET }}" > docker-data/secret.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        continue-on-error: true
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Buoy Barn
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: false
          tags: gmri/neracoos-buoy-barn:latest
          cache-from: type=local,src=${ BUILDX_CACHE }
          cache-to: type=local,dest=${ BUILDX_CACHE }
          outputs: type=docker

      - name: Bring up server
        run: docker-compose up -d

      - name: Wait for database to be ready
        run: docker-compose run web python manage.py db_ready

      - name: Test
        run: docker-compose run -e DJANGO_ENV=test web pytest --cov=. --cov-config=tox.ini --cov-report=xml:./coverage.xml

      - name: Install Codacy coverage reporter
        run: pip install --user codacy-coverage

      - name: Send coverage to Codacy
        run: ~/.local/bin/python-codacy-coverage -r app/coverage.xml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
